config/routes.rb
XFrame::Application.routes.draw do

  mount XAuth::Engine => "/auth"
  resources :demos

  get "main/index"
  root to: 'main#index'

end

app/models/demo.rb
class Demo < ActiveRecord::Base
  attr_accessible :age, :name, :sex
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  # GET /demos
  # GET /demos.json
  def index
    @demos = Demo.all
    @usermanger = true

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @demos }
    end
  end

  # GET /demos/1
  # GET /demos/1.json
  def show
    @demo = Demo.find(params[:id])
    @usermanger = true

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @demo }
    end
  end

  # GET /demos/new
  # GET /demos/new.json
  def new
    @demo = Demo.new
    @usermanger = true

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @demo }
    end
  end

  # GET /demos/1/edit
  def edit
    @demo = Demo.find(params[:id])
    @usermanger = true
  end

  # POST /demos
  # POST /demos.json
  def create
    @demo = Demo.new(params[:demo])

    respond_to do |format|
      if @demo.save
        format.html { redirect_to @demo, notice: 'Demo was successfully created.' }
        format.json { render json: @demo, status: :created, location: @demo }
      else
        format.html { render action: "new" }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /demos/1
  # PUT /demos/1.json
  def update
    @demo = Demo.find(params[:id])

    respond_to do |format|
      if @demo.update_attributes(params[:demo])
        format.html { redirect_to @demo, notice: 'Demo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demos/1
  # DELETE /demos/1.json
  def destroy
    @demo = Demo.find(params[:id])
    @demo.destroy

    respond_to do |format|
      format.html { redirect_to demos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/x_auth/main_helper.rb
module XAuth::MainHelper
end

app/views/demos/_form.html.erb
<%= form_for(@demo, html: {class: 'form-horizontal'}) do |f| %>
  <% if @demo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@demo.errors.count, "error") %> prohibited this demo from being saved:</h2>

      <ul>
        <% @demo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label(:name, class: 'control-label') %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label(:age, class: 'control-label') %>
    <div class="controls"><%= f.number_field :age %></div>
  </div>
  <div class="control-group">
    <%= f.label(:sex, class: 'control-label') %>
    <div class="controls"><%= f.text_field :sex %></div>
  </div>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">Save changes</button>
    <a href="<%= demos_path -%>" class="btn">返回</a>
  </div>
<% end %>

app/views/demos/edit.html.erb
<h2>Editing demo</h2>

<%= render 'form' %>

app/views/demos/index.html.erb
<h2>用户列表</h2>
<table class="table table-striped table-bordered table-hover">
  <tr>
    <th>No.</th>
    <th>Name</th>
    <th>sex</th>
    <th>age</th>
    <th colspan="3">Action</th>
  </tr>

  <% @demos.each_with_index do |item, idx| %>
    <tr>
      <td><%= idx + 1 -%></td>
      <td><%= item.name -%></td>
      <td><%= item.sex -%></td>
      <td><%= item.age -%></td>

      <td><%= link_to 'Show', demo_path(item.id) %></td>
      <td><%= link_to 'Edit', edit_demo_path(item) %></td>
      <td>
        <%= link_to('Destroy', item, method: :delete, data: {confirm: 'Are you sure?'}) %>
      </td>
    </tr>
  <% end %>
</table>

<p>
  <a href="<%= new_demo_path -%>" class="btn btn-primary btn-large">新建用户 &raquo;</a>
</p>

app/views/demos/new.html.erb
<h2>New demo</h2>

<%= render 'form' %>

app/views/demos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @demo.name %>
</p>

<p>
  <b>Age:</b>
  <%= @demo.age %>
</p>

<p>
  <b>Sex:</b>
  <%= @demo.sex %>
</p>

<p>
  <a href="<%= edit_demo_path(@demo) -%>" class="btn btn-primary btn-large">编辑</a>
  <a href="<%= demos_path -%>" class="btn btn-primary btn-large">返回</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Customer IQ</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag params[:controller], :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag params[:controller] -%>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="#">Customer IQ</a>

      <div class="nav-collapse collapse">
        <p class="navbar-text pull-right">
          <!--Logged in as <a href="#" class="navbar-link">Username</a>-->
          <a href="#loginPanel" class="navbar-link" data-toggle="modal">
            <i class="icon-user icon-white"></i>
            Login
          </a>
        </p>
        <ul class="nav">
          <li class="active">
            <a href="/main/index"><i class="icon-home icon-white"></i>Home</a>
          </li>
          <li>
            <a href="#about">
              <i class="icon-thumbs-up icon-white"></i>
              About
            </a>
          </li>
          <li><a href="#contact">
            <i class="icon-envelope icon-white"></i>
            Contact
          </a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <li class="nav-header">常用功能</li>
          <li class="<%= @usermanger ? 'active' : '' -%>">
            <a href="<%= demos_path -%>">用户管理</a>
          </li>
          <li><a href="#">权限管理</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li class="nav-header">系统设置</li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li class="nav-header">其它</li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
        </ul>
      </div>
    </div>
    <div class="span10">
      <div class="hero-unit">
        <%= yield -%>
      </div>
    </div>
  </div>
</div>


<div id="loginPanel" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Welcome To Login</h3>
  </div>
  <div class="modal-body">
    <div class="container" style="width:520px;">
      <form class="form-signin">
        <input type="text" class="input-block-level" placeholder="Email address">
        <input type="password" class="input-block-level" placeholder="Password">
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-large btn-primary" type="submit">Sign in</button>
      </form>
    </div>
  </div>
</div>
<script type="text/javascript">
  $('#loginPanel').on('shown', function(){
    var form = $("form.form-signin");
    form.children('input').first().focus();
  })
</script>

</body>
</html>

app/views/main/index.html.erb
<h1>About Customer IQ!</h1>
<p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit
  and three supporting pieces of content. Use it as a starting point to create something more unique.</p>

<p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit
  and three supporting pieces of content. Use it as a starting point to create something more unique.</p>

<br/>

<p>
  <a href="#" class="btn btn-primary btn-large">Learn more &raquo;</a>
</p>